#Create secret with username and password, to be accessed in Spring Boot application
#To assign values to secret keys use base64 format, and assign the result to the key
#For example: run command `echo -n 'root' | base64`
apiVersion: v1
kind: Secret
metadata:
  name: mongosecret
type: Opaque
data:
  username: cm9vdA==
  password: bW9uZ29kYg==
